version: '3.3'

services:

  server:
    image: $IMAGE_FULL_NAME
    restart: always
    environment:
      - ACCESS_TOKEN
      - VIRTUAL_HOST=$DOMAIN_NAME
      - LETSENCRYPT_HOST=$DOMAIN_NAME
      - LETSENCRYPT_EMAIL
    logging:
      driver: awslogs
        options:
          awslogs-region: us-east-1
          awslogs-group: /ec2/$DOMAIN_NAME
          awslogs-stream: /mq/server
          awslogs-datetime-format: "%Y-%m-%dT%H:%M:%S.%fZ"

networks:
  default:
    external:
      name: webproxy
